FROM nvidia/cuda:10.2-cudnn7-runtime-ubuntu18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y software-properties-common

RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update --fix-missing
RUN apt-get install -y git xvfb ffmpeg python-opencv python3.6 python3-pip python3.6-dev
RUN apt install -y libopenmpi-dev

# make python 3.6 the default version
RUN rm /usr/bin/python3
RUN rm /usr/bin/python
RUN ln -s /usr/bin/python3.6 /usr/bin/python3
RUN ln -s /usr/bin/python3.6 /usr/bin/python

# upgrade pip
RUN python -m pip install --upgrade pip

# python packages

COPY slowfast_requirements.txt requirements.txt
RUN pip install -r requirements.txt

RUN git clone https://github.com/facebookresearch/detectron2 detectron2_repo
COPY detectron2_repo detectron2_repo

RUN python -m pip install -e detectron2_repo