FROM aksrajawat/blender:1
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update
RUN apt install xfce4 xfce4-goodies -y
RUN apt install xvfb -y
ENV DISPLAY :0